on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: "aix"
            goarch: "ppc64"
          - goos: "android"
            goarch: "386"
          - goos: "android"
            goarch: "amd64"
          - goos: "android"
            goarch: "arm"
          - goos: "android"
            goarch: "arm64"
          - goos: "darwin"
            goarch: "amd64"
          - goos: "darwin"
            goarch: "arm64"
          - goos: "dragonfly"
            goarch: "amd64"
          - goos: "freebsd"
            goarch: "386"
          - goos: "freebsd"
            goarch: "amd64"
          - goos: "freebsd"
            goarch: "arm"
          - goos: "freebsd"
            goarch: "arm64"
          - goos: "illumos"
            goarch: "amd64"
          - goos: "ios"
            goarch: "amd64"
          - goos: "ios"
            goarch: "arm64"
          - goos: "js"
            goarch: "wasm"
          - goos: "linux"
            goarch: "386"
          - goos: "linux"
            goarch: "amd64"
          - goos: "linux"
            goarch: "arm"
          - goos: "linux"
            goarch: "arm64"
          - goos: "linux"
            goarch: "loong64"
          - goos: "linux"
            goarch: "mips"
          - goos: "linux"
            goarch: "mips64"
          - goos: "linux"
            goarch: "mips64le"
          - goos: "linux"
            goarch: "mipsle"
          - goos: "linux"
            goarch: "ppc64"
          - goos: "linux"
            goarch: "ppc64le"
          - goos: "linux"
            goarch: "riscv64"
          - goos: "linux"
            goarch: "s390x"
          - goos: "netbsd"
            goarch: "386"
          - goos: "netbsd"
            goarch: "amd64"
          - goos: "netbsd"
            goarch: "arm"
          - goos: "netbsd"
            goarch: "arm64"
          - goos: "openbsd"
            goarch: "386"
          - goos: "openbsd"
            goarch: "amd64"
          - goos: "openbsd"
            goarch: "arm"
          - goos: "openbsd"
            goarch: "arm64"
          - goos: "openbsd"
            goarch: "mips64"
          - goos: "plan9"
            goarch: "386"
          - goos: "plan9"
            goarch: "amd64"
          - goos: "plan9"
            goarch: "arm"
          - goos: "solaris"
            goarch: "amd64"
          - goos: "windows"
            goarch: "386"
          - goos: "windows"
            goarch: "amd64"
          - goos: "windows"
            goarch: "arm"
          - goos: "windows"
            goarch: "arm64"
    steps:
      - uses: actions/checkout@v3
        with:
          repository: google/skicka
      - uses: actions/setup-go@v3
      - name: Go Mod Init
        run: |
          go mod init github.com/google/skicka
          go mod tidy
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir build
          go build -o build/skicka-${{ matrix.goos }}-${{ matrix.goarch }}
      - uses: actions/upload-artifact@v2
        with:
          name: skicka-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/skicka-${{ matrix.goos }}-${{ matrix.goarch }}
